### PR TITLE
Adding global resolves to the router

### PR DESCRIPTION
**Pull request by orionstein**
This allows us to add global resolve functions in the form of

```
addGlobalResolve(async router => ({
    themes: await resolveClientThemes(largeThemes, router),
}))
```

Global resolves stack and act like regular resolve functions. If a global resolve adds a key to a resolved route, and the route also resolves the same property, the route resolve would override the global resolve.

We don't have global component resolve support as we don't have a route index tied to a global resolve. A `component` property would end up doing nothing.

### CODE REVIEW

**Comment by ninomichaels** [comment]
@orionstein code looks fine, but I just want to understand the use case, so this is in the event that we need something to resolve on every single route? 

and if that route is already accomplishing it, it won't double up.

**Comment by tadjohnston** [comment]
Agree with @ninomichaels. Other than that code looks fine!

**Comment by orionstein** [comment]
Yes, we want to be able to use it to resolve the theme loading on every route on large/small, without needing to put it into the resolve of every single route of ag manually.

If you double up, it will run it but replace it with the route version. Theoretically for this case we would just never have it doubled up on the route, but if we ever get a case in the future that we would use it for something else we could modify it then

**Comment by orionstein** [comment]
We effectively have to do this over and over for the theme loading between routes

https://github.com/rentpath/ag.js/blob/master/src/apps/large/Routes/routes.js#L131

And it's risky this way because if one is dropped, we can risk not loading SPA correctly. We need a way to do this once for all routes, and for this use case we would just be resolving the theme with the global resolve and removing it from all of our routes

**Pull request merged**
